### ISSUE TITLE
Not sure if Wildcards working or not

### ISSUE THREAD

**Issue by enzyme69** [AUTOMATIC1111/stable-diffusion-webui-wildcards#11]
I cannot find a clear tutorial on this Wildcards thing, besides some cool stuffs people wrote about this feature at Reddit.

I did try all the steps:
- dynamic prompting
- wildcard manager set to parrotzone
- actually use the __blah__ in the prompt

For example:
"portrait of cute lady with marvelous  __color__ hair"
<img width="472" alt="Screenshot 2022-12-22 at 11 57 14 pm" src="https://user-images.githubusercontent.com/3952687/209139119-2de293b6-8d47-4564-9c3a-20e4d77f0614.png">
 
I activated "Write Prompts To File" as well, hoping I could get a list of all the prompts generated via wildcards modifier, however none seems to be working?
<img width="473" alt="Screenshot 2022-12-22 at 11 58 04 pm" src="https://user-images.githubusercontent.com/3952687/209139284-24043214-afe8-4e53-af8c-68d6365fe6ee.png">

**Comment by enzyme69** [comment]
then I tried:
portrait of cute lady with marvelous  __tags/color__ hair

```
Error:
Error completing request
Arguments: (0, 'portrait of cute lady with marvelous  __tags/color__ hair', '', 'None', 'None', None, None, None, None, None, 0, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, 1202836262.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 0, '<div class="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{2$$artist1|artist2|artist3}</code><br/>\n\n    If $$ is not provided, then 1$$ is assumed.<br/><br/>\n\n    If the chosen number of terms is greater than the available terms, then some terms will be duplicated, otherwise chosen terms will be unique. This is useful in the case of wildcards, e.g.\n    <code class="codeblock">{2$$__artist__}</code> is equivalent to <code class="codeblock">{2$$__artist__|__artist__}</code><br/><br/>\n\n    A range can be provided:\n    <code class="codeblock">{1-3$$artist1|artist2|artist3}</code><br/>\n    In this case, a random number of artists between 1 and 3 is chosen.<br/><br/>\n\n    Wildcards can be used and the joiner can also be specified:\n    <code class="codeblock">{{1-$$and$$__adjective__}}</code><br/>\n\n    Here, a random number between 1 and 3 words from adjective.txt will be chosen and joined together with the word \'and\' instead of the default comma.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    Find and manage wildcards in the Wildcards Manager tab.\n\n    <br/><br/>\n\n    <small>You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in /Users/jimmygunawan/Documents/stable-diffusion-webui/extensions/sd-dynamic-prompts/wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', True, False, 1, False, False, False, 100, 0.7, False, False, False, False, False, False, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False, False, 0, 4, 384, 384, False, False, True, True, True, False, True, 1, False, False, 6.4, 38.5) {}
Traceback (most recent call last):
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/img2img.py", line 152, in img2img
    processed = process_images(p)
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/processing.py", line 532, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/Users/jimmygunawan/Documents/stable-diffusion-webui/modules/processing.py", line 832, in init
    image = img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

```
