### ISSUE TITLE
Deforum does not generate videos after the last update.

### ISSUE THREAD

**Issue by bismark211** [AUTOMATIC1111/stable-diffusion-webui-wildcards#17]
0
100%|████████████████████████████████████████████████████████████████████████████████| 110/110 [00:18<00:00,  5.85it/s]
2023-01-28 22:26:40,872 - root - INFO - Calibrating color correction.               | 110/6666 [00:18<18:06,  6.03it/s]
Rendering animation frame 2 of 300
  creating in between frame 0 tween:0.50
  resized to 500x1000
  creating in between frame 1 tween:1.00
  resized to 500x1000
  resized to 500x1000
Deforum progress:   2%|█                                                            | 110/6666 [00:19<18:57,  5.76it/s]
Error completing request
Arguments: ('task(c4663zv6flaeiz1)', None, False, '', '3D', 300, 'wrap', '0:(0)', '0:(1.02+0.02*sin(2*3.14*t/20))', '0:(0)', '0:(0)', '0:(1)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(t%15)', '0:(0)', '0:(53)', '0: (0.02)', '0: (0.6)', '0: (1.0)', '0: (7)', False, '0: (25)', '0: (40)', '0: (200)', '0: (10000)', '0: (t%4294967293)', False, '0: ("Euler a")', '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', True, 'Match Frame 0 LAB', 1.0, 2.0, 'perlin', 8.0, 8.0, 4, 0.5, True, 0.3, 200.0, 10000.0, 40.0, 'border', 'bicubic', False, '/content/video_in.mp4', 1, 0, -1, False, False, '/content/video_in.mp4', False, 4, False, '20220829210106', "{'0': '(Tokio cyberpunk:1.0), (cyberpunk road), (cyberpunk night club), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck', '50': '(cyberpunk (((cool DJ)))), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck', '100': '(night club sexy dancing show), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck', '150': '(punk rocker with a Mohawk playing electric guitar on fire), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck', '200': '(cyberpunk computer scientist who served as systems engineer dancer on the neo Tokyo streets, futuristic neon coat, reflective, decorated with traditional Japanese ornaments, cyberpunk fireworks), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck'}", '{\n    "0": "(Tokio cyberpunk:1.0), (cyberpunk road), (cyberpunk night club), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck",\n    "50": "(cyberpunk (((cool DJ)))), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck",\n    "100": "(night club sexy dancing show), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck",\n    "150": "(punk rocker with a Mohawk playing electric guitar on fire), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck",\n    "200": "(cyberpunk computer scientist who served as systems engineer dancer on the neo Tokyo streets, futuristic neon coat, reflective, decorated with traditional Japanese ornaments, cyberpunk fireworks), epic volumetric lighting, masterpiece, elite, hyper realistic, dynamic, 8k, centralized, professional, studio quality, sharp focus, high resolution, cinema4d, octane render, unreal engine, 3D sculpture, elite, dreamlikeart, cartoon, detail artwork by theCHAMBA --neg lowres, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, out of frame, mutated hands, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, long neck"\n}', 512, 1024, False, False, True, 0, 0, -1, 'Euler a', False, 1, 0.01, 0, 0, 110, 0.0, 1, False, 1, True, True, False, False, False, False, 'Deforum', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0.6, 'https://user-images.githubusercontent.com/14872007/195867706-d067cdc6-28cd-450b-a61e-55e25bc67010.png', False, False, False, True, 'https://www.filterforge.com/wiki/images/archive/b/b7/20080927223728%21Polygonal_gradient_thumb.jpg', 1.0, 1.0, 5.0, 1, True, 4, 'reroll', False, 28.0, 'FFMPEG mp4', 'C:\\stable-diffusion-webui\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', 17.0, 'veryslow', 'None', 'snowfall.mp3', False, False, 300.0, 'x0_pred', '/content/drive/MyDrive/AI/StableDiffusion/2022-09/20220903000939_%05d.png', '/content/drive/MyDrive/AI/StableDiffusion/content/drive/MyDrive/AI/StableDiffusion/2022-09/kabachuha/2022-09/20220903000939.mp4', False, 'RIFE v4.6', 'x3', 'x2', False, '', True, False, 'None', False, 'None', 'Farneback', False, 'None', False, 'None', False, False, '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://cdn.discordapp.com/attachments/1047760262637297664/1049851726200578058/a_dragon_flying_over_a_futuristic_city_dramatic_sky_cinematic_view_seed-1703716904ts-1670374556_idx-0.png",\n    "50": "https://cdn.discordapp.com/attachments/1047760262637297664/1049901219004555274/a_digital_painting_of_a_fox_standing_in_the_grass_on_a_hill__trees_beh_t_outpaint_from-down_seed-1205071278ts-1670386356_idx-0.png",\n    "100": "https://cdn.discordapp.com/attachments/745415989633482882/1048084925359857704/00024-2977479109-wings_hubble_images_jwst_images_6.png",\n    "150": "https://cdn.discordapp.com/attachments/1011355905490694355/1047133257097031680/31_0031_31.jpg",\n    "200": "https://cdn.discordapp.com/attachments/1047760262637297664/1049851726200578058/a_dragon_flying_over_a_futuristic_city_dramatic_sky_cinematic_view_seed-1703716904ts-1670374556_idx-0.png"\n}', '0:(.75)', '0:(.35)', '0:(.25)', '0:(20)', '0:(.075)', '<p style="font-weight:bold;margin-bottom:0.75em">Deforum v0.5-webui-beta</p>', '<strong>Made by <a href="https://deforum.github.io">deforum.github.io</a>, port for AUTOMATIC1111\'s webui maintained by <a href="https://github.com/kabachuha">kabachuha</a></strong>', '<ul style="list-style-type:circle; margin-left:1em">\n        <li>The code for this extension: <a  style="color:blue" href="https://github.com/deforum-art/deforum-for-automatic1111-webui">Fork of deforum for auto1111\'s webui</a>.</li>\n        <li>Join the <a style="color:blue" href="https://discord.gg/deforum">official Deforum Discord</a> to share your creations and suggestions.</li>\n        <li>For general usage, see the <a style="color:blue" href="https://docs.google.com/document/d/1pEobUknMFMkn8F5TMsv8qRzamXX_75BShMMXV8IFslI/edit">User guide for Deforum v0.5</a>.</li>\n        <li>For advanced animations, see the <a style="color:blue" href="https://docs.google.com/document/d/1pfW1PwbDIuW0cv-dnuyYj1UzPqe23BlSLTJsqazffXM/edit?usp=sharing">Math keyframing explanation</a>.</li>\n        <li>Alternatively, use <a style="color:blue" href="https://sd-parseq.web.app/deforum">sd-parseq</a> as a UI to define your animation schedules (see the Parseq section in the Keyframes tab).</li>\n        <li><a style="color:blue" href="https://www.framesync.xyz/">framesync.xyz</a> is also a good option, it makes compact math formulae for Deforum keyframes by selecting various waveforms.</li>\n        <li>The other site allows for making keyframes using <a style="color:blue" href="https://www.chigozie.co.uk/keyframe-string-generator/">interactive splines and Bezier curves</a> (select Disco output format).</li>\n        <li>After the 2022-12-30 update, the default noise type is <a style="color:blue" href="https://en.wikipedia.org/wiki/Perlin_noise">Perlin noise</a> due to its great frame coherence improvements. If you want to use the old noise and replicate the previous settings, set the type to "uniform" in the Keyframes tab.</li>\n        </ul>\n        <italic>If you liked this extension, please <a style="color:blue" href="https://github.com/deforum-art/deforum-for-automatic1111-webui">give it a star on GitHub</a>!</italic> 😊', '', '', '', '', '<p style="font-weight:bold;margin-bottom:0.75em">Import settings from file</p>', '<p style="font-weight:bold;margin-bottom:0.75em">Animation settings</p>', '<p style="margin-bottom:0.75em">Motion parameters:</p>', '<p style="margin-bottom:0.75em">2D and 3D settings</p>', '<p style="margin-bottom:0.75em">Prespective flip — Low VRAM pseudo-3D mode:</p>', '<p style="margin-bottom:0.75em">Coherence:</p>', '<p style="margin-bottom:0.75em">3D Depth Warping:</p>', '<p style="margin-bottom:0.75em">Video Input:</p>', '<p style="margin-bottom:0.75em">Interpolation (turned off atm)</p>', '<p style="margin-bottom:0.75em">Resume animation:</p>', '<p style="font-weight:bold;margin-bottom:0.75em">Prompts</p>', '<p>`animation_mode: None` batches on list of *prompts*. (Batch mode disabled atm, only animation_prompts are working)</p>', '<p style="font-weight:bold">*Important change from vanilla Deforum!*</p>', '<p style="font-weight:italic">This script uses the built-in webui weighting settings.</p>', '<p style="font-weight:italic">So if you want to use math functions as prompt weights,</p>', '<p style="font-weight:italic">keep the values above zero in both parts</p>', '<p style="font-weight:italic">Negative prompt part can be specified with --neg</p>', '<p style="font-weight:bold;margin-bottom:0.75em">Run settings</p>', '<p style="margin-bottom:0.75em">Sampling settings</p>', '<p style="margin-bottom:0.75em">3D Fov settings:</p>', '', '', '', '<p style="margin-bottom:0.75em">Batch settings</p>', '<p style="margin-bottom:0.75em">Init settings</p>', '<p style="margin-bottom:0.75em">3D settings</p>', '<p style="margin-bottom:0.75em">Steps scheduling:</p>', '<p style="margin-bottom:0.75em">Video output settings</p>', '<p style="margin-bottom:0.75em">To enable seed schedule select seed behavior — \'schedule\'</p>', '\n            Use an <a style=\'color:blue;\' target=\'_blank\' href=\'https://sd-parseq.web.app/deforum\'>sd-parseq manifest</a> for your animation (leave blank to ignore).</p>\n            <p style="margin-top:1em">\n                Note that parseq overrides:\n                <ul style="list-style-type:circle; margin-left:2em; margin-bottom:1em">\n                    <li>Run: seed, subseed, subseed strength.</li>\n                    <li>Keyframes: generation settings (noise, strength, contrast, scale).</li>\n                    <li>Keyframes: motion parameters for 2D and 3D (angle, zoom, translation, rotation, perspective flip).</li>\n                </ul>\n            </p>\n            <p">\n                Parseq does <strong><em>not</em></strong> override:\n                <ul style="list-style-type:circle; margin-left:2em; margin-bottom:1em">\n                    <li>Run: Sampler, W, H, Restore faces, tiling, highres fix, resize seed.</li>\n                    <li>Keyframes: animation settings (animation mode, max_frames, border) </li>\n                    <li>Keyframes: coherence (color coherence & diffusion cadence) </li>\n                    <li>Keyframes: depth warping</li>\n                    <li>Video output settings: all settings (including fps and max frames)</li>\n                </ul>\n            </p>\n            ', '<p style="margin-bottom:0.75em">Anti-blur settings</p>', '<p style="margin-bottom:0.75em">Perlin noise params, if selected.</p>', '<p style="padding-bottom:0"><b style="text-shadow: blue -1px -1px;">Hybrid Video Compositing in 2D/3D Mode</b><span style="color:#DDD;font-size:0.7rem;text-shadow: black -1px -1px;margin-left:10px;">by reallybigname</span></p>', '<ul style="list-style-type:circle; margin-left:1em; margin-bottom:1em;"><li>Composite video with previous frame init image in <b>2D or 3D animation_mode</b> <i>(not for Video Input mode)</i></li><li>Uses your <b>Init</b> settings for <b>video_init_path, extract_nth_frame, overwrite_extracted_frames</b></li><li>In Keyframes tab, you can also set <b>color_coherence</b> = \'<b>Video Input</b>\'</li><li><b>color_coherence_video_every_N_frames</b> lets you only match every N frames</li><li>Color coherence may be used with hybrid composite off, to just use video color.</li><li>Hybrid motion may be used with hybrid composite off, to just use video motion.</li></ul>Hybrid Video Schedules<ul style="list-style-type:circle; margin-left:1em; margin-bottom:1em;"><li>The alpha schedule controls overall alpha for video mix, whether using a composite mask or not.</li><li>The <b>hybrid_comp_mask_blend_alpha_schedule</b> only affects the \'Blend\' <b>hybrid_comp_mask_type</b>.</li><li>Mask contrast schedule is from 0-255. Normal is 1. Affects all masks.</li><li>Autocontrast low/high cutoff schedules 0-100. Low 0 High 100 is full range. <br>(<i><b>hybrid_comp_mask_auto_contrast</b> must be enabled</i>)</li></ul>See main Deforum document for more details.', '<p style="margin-bottom:0.75em"><b>Hybrid Video Schedules</b></p>', '\n            Use RIFE and other Video Frame Interpolation methods to smooth out, slow-mo (or both) your output videos.</p>\n             <p style="margin-top:1em">\n                Supported engines:\n                <ul style="list-style-type:circle; margin-left:1em; margin-bottom:1em">\n                    <li>RIFE v4.6, v4.3 and v4.0. Recommended for now: v4.6.</li>\n                    <li>RIFE v2.3 and other interpolation engines might come in the future.</li>\n                </ul>\n            </p>\n             <p style="margin-top:1em">\n                Important notes:\n                <ul style="list-style-type:circle; margin-left:1em; margin-bottom:1em">\n                    <li>ffmpeg has to be installed for this feature to work properly. If you can\'t have it, make sure to check the "keep_imgs" tab so that your interpolated frames are saved into HD\'\n                    <li>Frame Interpolation will *not* run if \'store_frames_in_ram\' is enabled.</li>\n                    <li>Audio (if provided) will be transferred to the interpolated video even if Slow-Mo is enabled.</li>\n                    <li>Frame Interpolation will always save an .mp4 video even if you used GIF for the raw video.</li>\n                </ul>\n            </p>\n            ', 'Supports boolean operations (! - negation, & - and, | - or, ^ - xor, \\ - difference, () - nested operations); default variables in \\{\\}, like \\{init_mask\\}, \\{video_mask\\}, \\{everywhere\\}; masks from files in [], like [mask1.png]; description-based <i>word masks</i> in &lt;&gt;, like &lt;apple&gt;, &lt;hair&gt;') {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 85, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, root.animation_prompts, root)
  File "C:\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 285, in render_animation
    noised_image = add_noise(contrast_image, noise, args.seed, anim_args.noise_type,
  File "C:\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\noise.py", line 62, in add_noise
    sample = cv2.addWeighted(sample, 1-noise_amt, noise_to_add, noise_amt, 0)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'

**Comment by bismark211** [comment]
can someone explain what is the problem?
